#!/bin/bash

target=$1

cd /srv/$target

git --git-dir=../$target/.git --work-tree=../$target pull origin main
# sudo -u andreas git --git-dir=../$target/.git --work-tree=../$target pull origin main

/home/andreas/.cargo/bin/cargo build --release
./script/build --mode=prod

sudo systemctl restart $target
