#!/bin/bash

target=$1

cd ../$target

sudo -u andreas git --git-dir=../$target/.git --work-tree=../$target pull origin main
sudo docker-compose build --build-arg VERSION=$(git log --format="%h" -n 1)
sudo docker-compose up -d
